AllCops:
  TargetRubyVersion: 3.0

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Metrics:
  Enabled: false

Naming/FileName:
  Enabled: false
